### ISSUE TITLE
eclipse Neon NOT Work.

### ISSUE THREAD

**Issue by jihwan** [benelog/multiline#12]
안녕하세요? 황지환입니다.
eclipse neon version 에서 compile시 동작 안하는 현상이 발생합니다.
compile시 아래와 같은 에러 로그가 발생합니다.

--------------------------------------------------------------------------------------
java.lang.NoClassDefFoundError: org/eclipse/jdt/internal/compiler/ast/Expression
	at org.adrianwalker.multilinestring.MultilineProcessor.init(MultilineProcessor.java:25)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.discoverNextProcessor(IdeAnnotationProcessorManager.java:94)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:116)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:135)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:915)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:437)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:417)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:368)
	at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.compile(IncrementalImageBuilder.java:330)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:305)
	at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.build(IncrementalImageBuilder.java:135)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildDeltas(JavaBuilder.java:267)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:195)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:487)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:399)
	at org.eclipse.ui.actions.GlobalBuildAction$1.run(GlobalBuildAction.java:177)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jdt.internal.compiler.ast.Expression
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more

**Comment by philsurette** [comment]
I'm seeing exactly the same issue. Works great in Mars (4.5.2) but you see this exception in Neon (4.6.0) - using ubuntu 16.04 and JDK 1.8. The exception doesn't make a lot of sense to me, it looks like something about the eclipse compiler has changed between releases.

Great annotation BTW, looks great in Mars.

**Comment by wezell** [comment]
Thirded.  Does not work in neon

**Comment by tobiascapin** [comment]
It doesn't work also from my Eclipse Neon. 

These link seems to be interesting but **without solution** :
http://stackoverflow.com/questions/38505155/working-with-annotation-processors-in-eclipse-4-6-neon
https://bugs.eclipse.org/bugs/show_bug.cgi?id=188558

**Comment by jaymeyer** [comment]
What happens if you change the pom.xml to remove <scope>provided ? like this:

<dependency>
    <groupId>org.eclipse.jdt.core.compiler</groupId>
    <artifactId>ecj</artifactId>
    <version>3.5.0</version>
</dependency>

**Comment by rimmeraj** [comment]
This pull request (https://github.com/benelog/multiline/pull/15) fixes the issue
